import Head from "next/head";
import Link from "next/link";
import PostoppsettComponent from "~/components/postoppsett/PostoppsettComponent";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Skurpost</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex flex-col items-center gap-2">
          <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white"></p>
            <Link
              href={sessionData ? "/api/auth/signout" : "/api/auth/signin"}
              className="w-96 rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
            >
              {sessionData ? "Sign out" : "Sign in"}
            </Link>
          </div>
        </div>
        <div>
          <Link href="/postoppsett">
            <button>Post</button>
          </Link>
        </div>
      </main>
    </>
  );
}
